version: '3.7'
services:
  server:
    image: gleidsonnunes/openencoder:latest
    container_name: server
    environment:
      - GIN_MODE=release
      - DATABASE_HOST=priv.net.ip.addr
      - REDIS_HOST=priv.net.ip.addr
    ports:
      - "8080:8080"
    entrypoint: ["/app", "server"]
    restart: always

  worker:
    image: gleidsonnunes/openencoder:latest
    container_name: worker
    environment:
      - DATABASE_HOST=priv.net.ip.addr
      - REDIS_HOST=priv.net.ip.addr
    entrypoint: ["/app", "worker"]
    restart: always

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD: 'postgres'
      - POSTGRES_DB: 'openencoder'
    volumes:
      - /var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: always