version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./htpasswd:/etc/nginx/htpasswd

  openencoder-web:
    image: alfg/openencoder:latest
    environment:
      - GIN_MODE=release
      - DATABASE_HOST=db
      - REDIS_HOST=redis
      - VIRTUAL_HOST=dev.openencode.com
      - CLOUDINIT_REDIS_HOST=priv.net.ip.addr
      - CLOUDINIT_DATABASE_HOST=priv.net.ip.addr
      - CLOUDINIT_WORKER_IMAGE=alfg/openencoder:latest
    links:
      - redis
      - db
    ports:
      - "8080:8080"
    entrypoint: ["/app", "server"]

  redis:
    image: "redis:alpine"
    ports:
      - priv.net.ip.addr:6379:6379
    volumes:
      - /data

  db:
    image: postgres
    ports:
      - priv.net.ip.addr:5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - /var/lib/postgresql/data