server_port: 8080
jwt_key: secretkey
keyseed: deadbeefdeadbeefdeadbeefdeadbeef
redis_host: localhost
redis_port: 6379
redis_max_active: 5
redis_max_idle: 5
database_host: localhost
database_port: 5432
database_user: postgres
database_password: postgres
database_name: openencoder
worker_namespace: openencoder
worker_job_name: encode
worker_concurrency: 1
work_dir: /tmp

cloudinit_redis_host: dev.openencode.com
cloudinit_redis_port: 6379
cloudinit_database_host: dev.openencode.com
cloudinit_database_port: 5432
cloudinit_database_user: postgres
cloudinit_database_password: postgres
cloudinit_database_name: openencoder
cloudinit_worker_image: alfg/openencoder:latest